#!/bin/bash

# $1 is the prefix name of the file

[ -z "$1" ] && echo "Missing target name parameter." && exit

mkdir -p build/pnr || exit

icebram soc/src/memory/i_ram_synth.hex build/images/$1"_instructions.hex" <build/pnr/hardware.asc> build/pnr/temp.asc
icebram soc/src/memory/d_ram_synth.hex build/images/$1"_data.hex" <build/pnr/temp.asc> build/pnr/$1".asc"

rm build/pnr/temp.asc || exit

mkdir -p build/binary || exit
icepack build/pnr/$1".asc" build/binary/$1".bin" || exit

iceprog build/binary/$1".bin" || exit